### ISSUE TITLE
can't seem to use pie.start() a second time.

### ISSUE THREAD

**Issue by msudol** [silverwind/tcpie#13]
Love this module.. I'm trying to setup a reusable class called Ping with module API for an app I'm building..  my goal is to ping a host 4 times quickly, wait 5 minutes, and ping it again.  It would seem that after the first pie.start() - I'm unable to run pie.start() again unless a create a new instance.  

Not sure if this has long run memory implications or not, just seems like I should be able to run it again.  I'm just dabbling at this point for fun - code is here - https://github.com/msudol/node-ping-monitor

**Comment by silverwind** [comment]
Fixed in v5.0.0. There was a check that prevented it from being restarted. I changed it so it justs resets stats and goes again when `.start()` is called.
