### ISSUE TITLE
Support for UDP protocol

### ISSUE THREAD

**Issue by cardil** [silverwind/tcpie#16]
Tcpie is nice tool. Sometimes it might be useful to use UDP instead of tcp.

**Comment by silverwind** [comment]
Not possible. UDP does not handshake and to get a UDP service to send something back you need to send it application-specific data which one can't generate without implementing those protocols.

**Comment by cardil** [comment]
You can test only if the connection can be opened. Without sending anything.

Similar what is described in this answer: https://serverfault.com/a/686216

**Comment by silverwind** [comment]
Listening for ICMP responses would require `root` priviledges and they are likely to be dropped by firewalls. I don't think this is something I want to do.
